// Dutch (nl) translations of CLI command descriptions, keyed by exact command token.
// Terminology follows the kiekr-i18n glossary (github.com/marcelverdult/kiekr-i18n).
// Descriptions are content (not UI chrome), so they live here rather than in i18n.ts.
// Generated to match every command in firmwareRegistry.ts (see the completeness test).

export const CLI_DESC_NL: Record<string, string> = {
  "ver": "Toon firmwareversie-string.",
  "board": "Toon board-/hardware-info.",
  "reboot": "Start het apparaat opnieuw op.",
  "clkreboot": "Kloksynchronisatie en vervolgens opnieuw opstarten.",
  "poweroff": "Schakel het apparaat uit (alleen nRF52).",
  "clock": "Toon huidige apparaatklok.",
  "clock sync": "Synchroniseer apparaatklok.",
  "time ": "Stel epoch-tijd in. Voorbeeld: time 1700000000",
  "get name": "Toon apparaatnaam/advert.",
  "get lat": "Toon geconfigureerde breedtegraad.",
  "get lon": "Toon geconfigureerde lengtegraad.",
  "get prv.key": "Toon privésleutel.",
  "get public.key": "Toon publieke sleutel.",
  "get role": "Toon apparaatrol.",
  "erase": "Wis opgeslagen configuratie (alleen serieel).",
  "get radio": "Toon huidige radioparameters.",
  "get freq": "Toon radiofrequentie.",
  "get tx": "Toon TX-vermogensniveau.",
  "get radio.rxgain": "Toon RX-versterking-instelling.",
  "set radio.rxgain on": "Schakel RX-versterkingsboost in.",
  "set radio.rxgain off": "Schakel RX-versterkingsboost uit.",
  "get dutycycle": "Toon huidige duty-cycle-limiet (%).",
  "set dutycycle ": "Stel duty-cycle-limiet in. Bereik: 1-100.",
  "get af": "Toon airtime-filterinstelling.",
  "set af ": "Stel airtime-filterwaarde in.",
  "get int.thresh": "Toon interferentiedrempel.",
  "set int.thresh ": "Stel interferentiedrempel in.",
  "get agc.reset.interval": "Toon AGC-reset-interval.",
  "set agc.reset.interval ": "Stel AGC-reset-interval in.",
  "tempradio ": "Wijzig radioparameters tijdelijk. Voorbeeld: tempradio 868100,125000,7,5,10 (freq,bw,sf,cr,timeout_mins)",
  "get advert.interval": "Toon advert-uitzendinterval.",
  "set advert.interval ": "Stel advert-interval in minuten in (60-240), of 0 om uit te schakelen.",
  "get flood.advert.interval": "Toon flood-advert-interval.",
  "set flood.advert.interval ": "Stel flood-advert-interval in uren in (3-168), of 0 om uit te schakelen. Standaard 47 (v1.16+).",
  "get path.hash.mode": "Toon pad-hash-modus.",
  "set path.hash.mode ": "Stel pad-hash-modus in.",
  "get rxdelay": "Toon RX-vertraging.",
  "set rxdelay ": "Stel RX-vertraging in.",
  "get txdelay": "Toon TX-vertraging.",
  "set txdelay ": "Stel TX-vertraging in.",
  "get direct.txdelay": "Toon directe TX-vertraging.",
  "set direct.txdelay ": "Stel directe TX-vertraging in.",
  "get repeat": "Toon repeat-modus (relay).",
  "set repeat on": "Schakel het herhalen van pakketten in.",
  "set repeat off": "Schakel het herhalen van pakketten uit.",
  "get flood.max": "Toon maximaal aantal flood-hops.",
  "set flood.max ": "Stel maximaal aantal flood-hops in.",
  "get flood.max.unscoped": "Toon limiet op unscoped flood-verkeer (v1.16+). Standaard 64.",
  "set flood.max.unscoped ": "Limiteer unscoped flood-verkeer (v1.16+). Standaard 64.",
  "get flood.max.advert": "Toon limiet op geflooded advert-pakketten (v1.16+). Standaard 8.",
  "set flood.max.advert ": "Limiteer geflooded advert-pakketten (v1.16+). Standaard 8.",
  "get allow.read.only": "Toon alleen-lezen-toegangsinstelling.",
  "set allow.read.only on": "Sta alleen-lezen-toegang toe.",
  "set allow.read.only off": "Weiger alleen-lezen-toegang.",
  "get loop.detect": "Toon lus-detectiemodus.",
  "set loop.detect ": "Stel lus-detectie in. Waarden: off/minimal/moderate/strict",
  "get multi.acks": "Toon multi-ack-instelling.",
  "set multi.acks ": "Stel multi-ack-waarde in.",
  "neighbors": "Toon bekende buren.",
  "neighbor.remove ": "Verwijder buur op pubkey.",
  "discover.neighbors": "Start buurontdekking (alleen repeater).",
  "get guest.password": "Toon gastwachtwoord.",
  "set guest.password ": "Stel gastwachtwoord in.",
  "get owner.info": "Toon eigenaar-info-string.",
  "set owner.info ": "Stel eigenaar-info-string in.",
  "password ": "Wijzig admin-wachtwoord.",
  "setperm ": "Stel ACL-rechten voor een node in. Voorbeeld: setperm <pubkey> <0-3>",
  "get acl": "Toon toegangscontrolelijst (alleen lokaal serieel).",
  "stats-core": "Toon batterij, uptime, wachtrij.",
  "stats-radio": "Toon ruisvloer, RSSI/SNR, airtime, fouten.",
  "stats-packets": "Toon pakket-RX/TX-tellers.",
  "clear stats": "Wis statistiektellers.",
  "log": "Dump logboek.",
  "log start": "Start logboekregistratie.",
  "log stop": "Stop logboekregistratie.",
  "log erase": "Wis opgeslagen logboek.",
  "start ota": "Start OTA-firmware-updatemodus.",
  "region": "Toon regiohiërarchie.",
  "region save": "Sla regioconfiguratie op.",
  "region home ": "Stel thuisregio in.",
  "region default ": "Stel standaardregio in.",
  "region def ": "Definieer een regio met verkorte nesting-notatie (v1.16+).",
  "region put ": "Registreer een regiocode. Voorbeeld: region put NL-ZH *",
  "region get ": "Haal een regio-item op.",
  "region remove ": "Verwijder een regio-item.",
  "region allowf ": "Zet een regiofilter op de toegestaan-lijst.",
  "region denyf ": "Zet een regiofilter op de geweigerd-lijst.",
  "region list": "Toon regio's.",
  "region load ": "Laad regio uit opslag.",
  "set name ": "Stel apparaatnaam/advert in.",
  "set lat ": "Stel breedtegraad in.",
  "set lon ": "Stel lengtegraad in.",
  "set prv.key ": "Stel privésleutel in.",
  "set freq ": "Stel radiofrequentie in (alleen serieel).",
  "set radio ": "Stel volledige radioparameters in: freq,bw,sf,cr.",
  "set tx ": "Stel TX-vermogen in (dBm).",
  "advert": "Verstuur nu een flood-advert.",
  "advert.zerohop": "Verstuur nu een zero-hop-advert.",
  "shutdown": "Schakel het apparaat uit.",
  "powersaving on": "Schakel energiebesparing in (build-afhankelijk).",
  "powersaving off": "Schakel energiebesparing uit (build-afhankelijk).",
  "get adc.multiplier": "Toon ADC-multiplier (build-afhankelijk).",
  "set adc.multiplier ": "Stel ADC-multiplier in (build-afhankelijk).",
  "get bootloader.ver": "Toon bootloader-versie (nRF52-builds).",
  "get pwrmgt.support": "Toon energiebeheer-ondersteuning (nRF52-builds).",
  "get pwrmgt.source": "Toon voedingsbron (nRF52-builds).",
  "get pwrmgt.bootreason": "Toon opstartreden (nRF52-builds).",
  "get pwrmgt.bootmv": "Toon opstartspanning in mV (nRF52-builds).",
  "gps on": "Schakel GPS in (build-afhankelijk).",
  "gps off": "Schakel GPS uit (build-afhankelijk).",
  "gps sync": "Synchroniseer tijd vanaf GPS (build-afhankelijk).",
  "gps setloc": "Stel locatie in vanaf GPS (build-afhankelijk).",
  "gps advert": "Adverteer GPS-locatie (build-afhankelijk).",
  "get bridge.type": "Toon bridge-type (build-afhankelijk).",
  "get bridge.enabled": "Toon of bridge is ingeschakeld (build-afhankelijk).",
  "set bridge.enabled ": "Schakel bridge in/uit (build-afhankelijk).",
  "set bridge.delay ": "Stel bridge-vertraging in (build-afhankelijk).",
  "set bridge.source ": "Stel bridge-bron in (build-afhankelijk).",
  "set bridge.baud ": "Stel RS232-bridge-baudrate in (build-afhankelijk).",
  "set bridge.channel ": "Stel ESP-NOW-bridge-kanaal in (build-afhankelijk).",
  "set bridge.secret ": "Stel ESP-NOW-bridge-secret in (build-afhankelijk).",
  "sensor list": "Toon sensorvariabelen.",
  "sensor get ": "Haal een sensorvariabele op.",
  "sensor set ": "Stel een sensorvariabele in.",
  "io ": "GPIO lezen/instellen/resetten/omschakelen. bijv. io / io s<hex> / io r<hex> / io t<hex>",
  "filter": "Toon pakketfilterstatus en blokkeringsoverzicht per type.",
  "filter on": "Schakel het RF-pakketfilter in.",
  "filter off": "Schakel het RF-pakketfilter uit.",
  "filter reset": "Herstel filterstandaardwaarden.",
  "filter hops ": "Stel max. aantal hops per payload-type in. Voorbeeld: filter hops 5 20 (type,max_hops). Kaal \"filter hops\" toont de huidige limieten.",
  "filter rate ": "Beperk de snelheid van een payload-type. Voorbeeld: filter rate 2 20 60 (type,limit,seconds). Kaal \"filter rate\" toont de configuratie.",
  "filter channel list": "Toon geblokkeerde kanalen.",
  "filter channel add ": "Blokkeer een kanaal op naam. Voorbeeld: filter channel add Public",
  "filter channel remove ": "Deblokkeer een kanaal op naam.",
  "filter hash ": "Stel minimaal aantal pad-hash-bytes in (1-3). Kaal \"filter hash\" toont de huidige waarde.",
  "filter malformed on": "Verwijder publiek-kanaal-tekst met onjuiste UTF-8.",
  "filter malformed off": "Sta onjuiste publiek-kanaal-tekst toe.",
  "filter count": "Toon blokkeringsstatistieken per payload-type.",
  "get radio.fem.rxgain": "Toon versterkingsstatus van externe-FEM RX-LNA.",
  "set radio.fem.rxgain on": "Schakel externe-FEM RX-LNA-versterking in.",
  "set radio.fem.rxgain off": "Schakel externe-FEM RX-LNA-versterking uit.",
  "get radio.fem.txgain": "Toon versterkingsstatus van externe-FEM TX-PA.",
  "set radio.fem.txgain on": "Schakel externe-FEM TX-PA-versterking in.",
  "set radio.fem.txgain off": "Schakel externe-FEM TX-PA-versterking uit.",
  "get radio.watchdog": "Toon radio-watchdog-timeout (minuten).",
  "set radio.watchdog ": "Stel radio-watchdog-timeout in minuten in (0-120, 0 = uit).",
  "set mqtt.origin ": "Stel MQTT-origin / apparaatnaam in topic in (leeg om te wissen).",
  "get mqtt.origin": "Toon effectieve MQTT-origin.",
  "set mqtt.iata ": "Stel MQTT IATA-code in.",
  "get mqtt.iata": "Toon MQTT IATA-code.",
  "set mqtt.status on": "Schakel periodieke statuspublicatie in.",
  "set mqtt.status off": "Schakel periodieke statuspublicatie uit.",
  "get mqtt.status": "Toon MQTT-verbindingsstatusrapport.",
  "set mqtt.packets on": "Schakel publicatie per pakket in.",
  "set mqtt.packets off": "Schakel publicatie per pakket uit.",
  "get mqtt.packets": "Toon publicatiestatus per pakket.",
  "set mqtt.raw on": "Schakel publicatie van ruwe payload in.",
  "set mqtt.raw off": "Schakel publicatie van ruwe payload uit.",
  "get mqtt.raw": "Toon publicatiestatus van ruwe payload.",
  "set mqtt.tx ": "TX-publicatie: on|off|advert.",
  "get mqtt.tx": "Toon TX-publicatiemodus (on/off/advert).",
  "set mqtt.rx on": "Schakel publicatie van ontvangen (RX) pakketten in.",
  "set mqtt.rx off": "Schakel publicatie van ontvangen (RX) pakketten uit.",
  "get mqtt.rx": "Toon RX-publicatiestatus.",
  "set mqtt.interval ": "Statusinterval, 1-60 minuten.",
  "get mqtt.interval": "Toon statusinterval.",
  "set mqtt.ntp ": "Stel NTP-server in (\"none\" = standaard pool.ntp.org).",
  "get mqtt.ntp": "Toon geconfigureerde NTP-server.",
  "get mqtt.ntp.diag": "Toon NTP-synchronisatiediagnostiek.",
  "set mqtt.owner ": "Stel publieke sleutel van eigenaar in (64 hex).",
  "get mqtt.owner": "Toon publieke sleutel van eigenaar (alleen serieel).",
  "set mqtt.email ": "Stel e-mailadres van eigenaar in.",
  "get mqtt.email": "Toon e-mailadres van eigenaar (alleen serieel).",
  "get mqtt.presets": "Toon ingebouwde broker-presets (bijv. dutchmeshcore-1, dutchmeshcore-2, meshcore-analyzer-eu).",
  "get mqtt.config.valid": "Toon of de MQTT-configuratie geldig is.",
  "set mqtt1.preset ": "Preset voor slot 1 (bijv. dutchmeshcore-1, meshcore-analyzer-eu, custom, none).",
  "set mqtt1.server ": "Broker-host voor slot 1 (custom preset).",
  "set mqtt1.port ": "Poort voor slot 1 (1-65535).",
  "set mqtt1.username ": "Gebruikersnaam voor slot 1.",
  "set mqtt1.password ": "Wachtwoord voor slot 1.",
  "set mqtt1.token ": "JWT-token voor slot 1.",
  "set mqtt1.topic ": "Topic-template voor slot 1 (alleen custom preset).",
  "set mqtt1.audience ": "JWT-audience voor slot 1 (leeg om te wissen).",
  "get mqtt1.diag": "Verbindingsdiagnostiek voor slot 1.",
  "set mqtt2.preset ": "Preset voor slot 2 (bijv. dutchmeshcore-2, meshcore-analyzer-eu, custom, none).",
  "set mqtt2.server ": "Broker-host voor slot 2 (custom preset).",
  "set mqtt2.port ": "Poort voor slot 2 (1-65535).",
  "set mqtt2.username ": "Gebruikersnaam voor slot 2.",
  "set mqtt2.password ": "Wachtwoord voor slot 2.",
  "set mqtt2.token ": "JWT-token voor slot 2.",
  "set mqtt2.topic ": "Topic-template voor slot 2 (alleen custom preset).",
  "set mqtt2.audience ": "JWT-audience voor slot 2 (leeg om te wissen).",
  "get mqtt2.diag": "Verbindingsdiagnostiek voor slot 2.",
  "set mqtt3.preset ": "Preset voor slot 3 (bijv. meshcore-analyzer-eu, custom, none).",
  "set mqtt3.server ": "Broker-host voor slot 3 (custom preset).",
  "set mqtt3.port ": "Poort voor slot 3 (1-65535).",
  "set mqtt3.username ": "Gebruikersnaam voor slot 3.",
  "set mqtt3.password ": "Wachtwoord voor slot 3.",
  "set mqtt3.token ": "JWT-token voor slot 3.",
  "set mqtt3.topic ": "Topic-template voor slot 3 (alleen custom preset).",
  "set mqtt3.audience ": "JWT-audience voor slot 3 (leeg om te wissen).",
  "get mqtt3.diag": "Verbindingsdiagnostiek voor slot 3.",
  "set mqtt4.preset ": "Preset voor slot 4 (bijv. meshcore-analyzer-eu, custom, none).",
  "set mqtt4.server ": "Broker-host voor slot 4 (custom preset).",
  "set mqtt4.port ": "Poort voor slot 4 (1-65535).",
  "set mqtt4.username ": "Gebruikersnaam voor slot 4.",
  "set mqtt4.password ": "Wachtwoord voor slot 4.",
  "set mqtt4.token ": "JWT-token voor slot 4.",
  "set mqtt4.topic ": "Topic-template voor slot 4 (alleen custom preset).",
  "set mqtt4.audience ": "JWT-audience voor slot 4 (leeg om te wissen).",
  "get mqtt4.diag": "Verbindingsdiagnostiek voor slot 4.",
  "set mqtt5.preset ": "Preset voor slot 5 (bijv. meshcore-analyzer-eu, custom, none).",
  "set mqtt5.server ": "Broker-host voor slot 5 (custom preset).",
  "set mqtt5.port ": "Poort voor slot 5 (1-65535).",
  "set mqtt5.username ": "Gebruikersnaam voor slot 5.",
  "set mqtt5.password ": "Wachtwoord voor slot 5.",
  "set mqtt5.token ": "JWT-token voor slot 5.",
  "set mqtt5.topic ": "Topic-template voor slot 5 (alleen custom preset).",
  "set mqtt5.audience ": "JWT-audience voor slot 5 (leeg om te wissen).",
  "get mqtt5.diag": "Verbindingsdiagnostiek voor slot 5.",
  "set mqtt6.preset ": "Preset voor slot 6 (bijv. meshcore-analyzer-eu, custom, none).",
  "set mqtt6.server ": "Broker-host voor slot 6 (custom preset).",
  "set mqtt6.port ": "Poort voor slot 6 (1-65535).",
  "set mqtt6.username ": "Gebruikersnaam voor slot 6.",
  "set mqtt6.password ": "Wachtwoord voor slot 6.",
  "set mqtt6.token ": "JWT-token voor slot 6.",
  "set mqtt6.topic ": "Topic-template voor slot 6 (alleen custom preset).",
  "set mqtt6.audience ": "JWT-audience voor slot 6 (leeg om te wissen).",
  "get mqtt6.diag": "Verbindingsdiagnostiek voor slot 6.",
  "set mqtt1.filter ": "Publicatiefilter voor slot 1: all | none | CSV van typenamen/-nummers. Voorbeeld: set mqtt1.filter txt_msg,advert",
  "get mqtt1.filter": "Toon publicatiefilter voor slot 1.",
  "set mqtt2.filter ": "Publicatiefilter voor slot 2: all | none | CSV van typenamen/-nummers.",
  "get mqtt2.filter": "Toon publicatiefilter voor slot 2.",
  "set mqtt3.filter ": "Publicatiefilter voor slot 3: all | none | CSV van typenamen/-nummers.",
  "get mqtt3.filter": "Toon publicatiefilter voor slot 3.",
  "set mqtt4.filter ": "Publicatiefilter voor slot 4: all | none | CSV van typenamen/-nummers.",
  "get mqtt4.filter": "Toon publicatiefilter voor slot 4.",
  "set mqtt5.filter ": "Publicatiefilter voor slot 5: all | none | CSV van typenamen/-nummers.",
  "get mqtt5.filter": "Toon publicatiefilter voor slot 5.",
  "set mqtt6.filter ": "Publicatiefilter voor slot 6: all | none | CSV van typenamen/-nummers.",
  "get mqtt6.filter": "Toon publicatiefilter voor slot 6.",
  "discover.scopes": "Ververs de buurtabel en publiceer deze nu naar MQTT (eenmalig).",
  "get mqtt.neighbors": "Toon status van periodieke buurpublicatie.",
  "set mqtt.neighbors on": "Schakel periodieke buurpublicatie in.",
  "set mqtt.neighbors off": "Schakel periodieke buurpublicatie uit.",
  "get mqtt.neighbors.interval": "Toon buurpublicatie-interval (uren).",
  "set mqtt.neighbors.interval ": "Stel buurpublicatie-interval in uren in (12-336).",
  "set wifi.ssid ": "Stel WiFi-SSID in (opnieuw opstarten om opnieuw te verbinden).",
  "set wifi.pwd ": "Stel WiFi-wachtwoord in (opnieuw opstarten om opnieuw te verbinden).",
  "set wifi.powersave ": "WiFi-energiebesparing: none|min|max.",
  "get wifi.ssid": "Toon WiFi-SSID.",
  "get wifi.pwd": "Toon WiFi-wachtwoord.",
  "get wifi.powersave": "Toon WiFi-energiebesparingsmodus.",
  "ota check": "Controleer ota.dutchmeshcore.nl op een nieuwere DutchMeshCore-release via de observer-WiFi-verbinding.",
  "ota update": "Download en installeer de nieuwste DutchMeshCore-firmware via de observer-WiFi-verbinding (pull-gebaseerde OTA).",
  "set timezone ": "Stel IANA-tijdzone in (bijv. Europe/Amsterdam).",
  "get timezone": "Toon tijdzone.",
  "set timezone.offset ": "Stel UTC-offset in (-12..14).",
  "get timezone.offset": "Toon UTC-offset.",
  "set snmp on": "Schakel de SNMP-agent in (opnieuw opstarten om toe te passen).",
  "set snmp off": "Schakel de SNMP-agent uit (opnieuw opstarten om toe te passen).",
  "get snmp": "Toon of SNMP is ingeschakeld.",
  "set snmp.community ": "Stel SNMP-community-string in.",
  "get snmp.community": "Toon SNMP-community-string.",
  "set alert on": "Schakel automatische storingswaarschuwingen in.",
  "set alert off": "Schakel automatische storingswaarschuwingen uit.",
  "get alert": "Toon of waarschuwingen zijn ingeschakeld.",
  "set alert.psk ": "PSK van waarschuwingskanaal (32 hex; leeg om te wissen).",
  "get alert.psk": "Toon waarschuwings-PSK (alleen serieel).",
  "set alert.hashtag ": "Leid de PSK van het waarschuwingskanaal af uit een #hashtag.",
  "get alert.hashtag": "Toon waarschuwings-hashtag.",
  "set alert.region ": "Overschrijf de scope-regio voor waarschuwingen.",
  "get alert.region": "Toon regio-override voor waarschuwingen.",
  "set alert.wifi ": "Drempel in minuten voor WiFi-down-waarschuwing (0-1440, 0 = uit).",
  "get alert.wifi": "Toon WiFi-waarschuwingsdrempel.",
  "set alert.mqtt ": "Drempel in minuten voor MQTT-down-waarschuwing (0-10080, 0 = uit).",
  "get alert.mqtt": "Toon MQTT-waarschuwingsdrempel.",
  "set alert.interval ": "Minimaal interval tussen herhalingen (60-10080 min).",
  "get alert.interval": "Toon herhalingsinterval van waarschuwingen.",
  "alert test": "Verstuur een eenmalige testwaarschuwing.",
}
