// German (de) translations of CLI command descriptions, keyed by exact command token.
// Descriptions are content (not UI chrome), so they live here rather than in i18n.ts.
// Generated to match every command in firmwareRegistry.ts (see the completeness test).

export const CLI_DESC_DE: Record<string, string> = {
  "ver": "Firmwareversion-String anzeigen.",
  "board": "Board-/Hardware-Info anzeigen.",
  "reboot": "Gerät neu starten.",
  "clkreboot": "Uhrensynchronisation und anschließender Neustart.",
  "poweroff": "Gerät ausschalten (nur nRF52).",
  "clock": "Aktuelle Geräteuhr anzeigen.",
  "clock sync": "Geräteuhr synchronisieren.",
  "time ": "Epoch-Zeit einstellen. Beispiel: time 1700000000",
  "get name": "Gerätename/Bekanntmachung anzeigen.",
  "get lat": "Konfigurierten Breitengrad anzeigen.",
  "get lon": "Konfigurierten Längengrad anzeigen.",
  "get prv.key": "Privaten Schlüssel anzeigen.",
  "get public.key": "Öffentlichen Schlüssel anzeigen.",
  "get role": "Geräterolle anzeigen.",
  "erase": "Gespeicherte Konfiguration löschen (nur seriell).",
  "get radio": "Aktuelle Funkparameter anzeigen.",
  "get freq": "Funkfrequenz anzeigen.",
  "get tx": "TX-Leistungspegel anzeigen.",
  "get radio.rxgain": "RX-Verstärkungseinstellung anzeigen.",
  "set radio.rxgain on": "RX-Verstärkungsboost einschalten.",
  "set radio.rxgain off": "RX-Verstärkungsboost ausschalten.",
  "get dutycycle": "Aktuelles Duty-Cycle-Limit (%) anzeigen.",
  "set dutycycle ": "Duty-Cycle-Limit einstellen. Bereich: 1-100.",
  "get af": "Airtime-Faktor anzeigen (Duty-Cycle-Budget).",
  "set af ": "Airtime-Faktor direkt einstellen (Duty-Cycle-Budget).",
  "get dc.gate": "Status des Duty-Cycle-Regionen-Gatings anzeigen.",
  "set dc.gate ": "Duty-Cycle-Regionen-Gating ein- oder ausschalten (0/1).",
  "get dc.gate.thresh": "TX-Duty % anzeigen, ab dem Gating aktiviert.",
  "set dc.gate.thresh ": "Gating-Schwelle einstellen (1-100 %). Standard 70.",
  "get dc.gate.hyst": "Hysteresespanne des Gatings anzeigen.",
  "set dc.gate.hyst ": "Gating-Hysterese einstellen (0-50 %). Regionen öffnen wieder unter Schwelle minus Hysterese. Standard 10.",
  "get dc.gate.status": "Live-TX-Duty % und aktuelle Gate-Stufe anzeigen.",
  "get int.thresh": "Interferenzschwelle anzeigen.",
  "set int.thresh ": "Interferenzschwelle einstellen.",
  "get agc.reset.interval": "AGC-Reset-Intervall anzeigen.",
  "set agc.reset.interval ": "AGC-Reset-Intervall einstellen.",
  "tempradio ": "Funkparameter vorübergehend ändern. Beispiel: tempradio 868100,125000,7,5,10 (freq,bw,sf,cr,timeout_mins)",
  "get advert.interval": "Bekanntmachungs-Sendeintervall anzeigen.",
  "set advert.interval ": "Bekanntmachungsintervall in Minuten einstellen (60-240), oder 0 zum Deaktivieren.",
  "get flood.advert.interval": "Flood-Bekanntmachungsintervall anzeigen.",
  "set flood.advert.interval ": "Flood-Bekanntmachungsintervall in Stunden einstellen (3-168), oder 0 zum Deaktivieren. Standard 47 (v1.16+).",
  "get path.hash.mode": "Pfad-Hash-Modus anzeigen.",
  "set path.hash.mode ": "Pfad-Hash-Modus einstellen.",
  "get rxdelay": "RX-Verzögerung anzeigen.",
  "set rxdelay ": "RX-Verzögerung einstellen.",
  "get txdelay": "TX-Verzögerung anzeigen.",
  "set txdelay ": "TX-Verzögerung einstellen.",
  "get direct.txdelay": "Direkte TX-Verzögerung anzeigen.",
  "set direct.txdelay ": "Direkte TX-Verzögerung einstellen.",
  "get repeat": "Repeat-Modus (Relay) anzeigen.",
  "set repeat on": "Weiterleitung von Paketen einschalten.",
  "set repeat off": "Weiterleitung von Paketen ausschalten.",
  "get flood.max": "Maximale Anzahl der Flood-Hops anzeigen.",
  "set flood.max ": "Maximale Anzahl der Flood-Hops einstellen.",
  "get flood.max.unscoped": "Limit für unscoped Flood-Verkehr anzeigen (v1.16+). Standard 64.",
  "set flood.max.unscoped ": "Unscoped Flood-Verkehr begrenzen (v1.16+). Standard 64.",
  "get flood.max.advert": "Limit für geflutete Bekanntmachungspakete anzeigen (v1.16+). Standard 8.",
  "set flood.max.advert ": "Geflutete Bekanntmachungspakete begrenzen (v1.16+). Standard 8.",
  "get allow.read.only": "Nur-Lesen-Zugriffseinstellung anzeigen.",
  "set allow.read.only on": "Nur-Lesen-Zugriff erlauben.",
  "set allow.read.only off": "Nur-Lesen-Zugriff verweigern.",
  "get loop.detect": "Schleifenerkennungsmodus anzeigen.",
  "set loop.detect ": "Schleifenerkennung einstellen. Werte: off/minimal/moderate/strict",
  "get multi.acks": "Multi-Ack-Einstellung anzeigen.",
  "set multi.acks ": "Multi-Ack-Wert einstellen.",
  "neighbors": "Bekannte Nachbarn anzeigen.",
  "neighbor.remove ": "Nachbar anhand des pubkey entfernen.",
  "discover.neighbors": "Nachbarermittlung starten (nur Repeater).",
  "get guest.password": "Gastpasswort anzeigen.",
  "set guest.password ": "Gastpasswort einstellen.",
  "get owner.info": "Eigentümer-Info-String anzeigen.",
  "set owner.info ": "Eigentümer-Info-String einstellen.",
  "password ": "Admin-Passwort ändern.",
  "setperm ": "ACL-Rechte für einen Node einstellen. Beispiel: setperm <pubkey> <0-3>",
  "get acl": "Zugriffssteuerungsliste anzeigen (nur lokal seriell).",
  "stats-core": "Batterie, Uptime, Warteschlange anzeigen.",
  "stats-radio": "Rauschgrund, RSSI/SNR, Airtime, Fehler anzeigen.",
  "stats-packets": "Paket-RX/TX-Zähler anzeigen.",
  "clear stats": "Statistikzähler löschen.",
  "log": "Protokoll ausgeben.",
  "log start": "Protokollierung starten.",
  "log stop": "Protokollierung stoppen.",
  "log erase": "Gespeichertes Protokoll löschen.",
  "start ota": "OTA-Firmware-Update-Modus starten.",
  "region": "Regionshierarchie anzeigen.",
  "region save": "Regionskonfiguration speichern.",
  "region home ": "Heimatregion einstellen.",
  "region default ": "Standardregion einstellen.",
  "region def ": "Eine Region mit verkürzter Nesting-Notation definieren (v1.16+).",
  "region put ": "Einen Regionscode registrieren. Beispiel: region put NL-ZH *",
  "region get ": "Ein Regionselement abrufen.",
  "region remove ": "Ein Regionselement entfernen.",
  "region allowf ": "Einen Regionsfilter auf die Erlaubt-Liste setzen.",
  "region denyf ": "Einen Regionsfilter auf die Verweigert-Liste setzen.",
  "region list": "Regionen anzeigen.",
  "region list allowed": "Regionen anzeigen, die Flood erlauben.",
  "region list denied": "Regionen anzeigen, die Flood blockieren.",
  "region load ": "Region aus dem Speicher laden.",
  "set name ": "Gerätename/Bekanntmachung einstellen.",
  "set lat ": "Breitengrad einstellen.",
  "set lon ": "Längengrad einstellen.",
  "set prv.key ": "Privaten Schlüssel einstellen.",
  "set freq ": "Funkfrequenz einstellen (nur seriell).",
  "set radio ": "Vollständige Funkparameter einstellen: freq,bw,sf,cr.",
  "set tx ": "TX-Leistung einstellen (dBm).",
  "advert": "Jetzt eine Flood-Bekanntmachung senden.",
  "advert.zerohop": "Jetzt eine Zero-Hop-Bekanntmachung senden.",
  "shutdown": "Gerät ausschalten.",
  "powersaving on": "Energiesparmodus einschalten (build-abhängig).",
  "powersaving off": "Energiesparmodus ausschalten (build-abhängig).",
  "get adc.multiplier": "ADC-Multiplikator anzeigen (build-abhängig).",
  "set adc.multiplier ": "ADC-Multiplikator einstellen (build-abhängig).",
  "get bootloader.ver": "Bootloader-Version anzeigen (nRF52-Builds).",
  "get pwrmgt.support": "Energieverwaltungsunterstützung anzeigen (nRF52-Builds).",
  "get pwrmgt.source": "Stromquelle anzeigen (nRF52-Builds).",
  "get pwrmgt.bootreason": "Startgrund anzeigen (nRF52-Builds).",
  "get pwrmgt.bootmv": "Startspannung in mV anzeigen (nRF52-Builds).",
  "gps on": "GPS einschalten (build-abhängig).",
  "gps off": "GPS ausschalten (build-abhängig).",
  "gps sync": "Zeit von GPS synchronisieren (build-abhängig).",
  "gps setloc": "Standort von GPS einstellen (build-abhängig).",
  "gps advert": "GPS-Standort bekannt machen (build-abhängig).",
  "get bridge.type": "Bridge-Typ anzeigen (build-abhängig).",
  "get bridge.enabled": "Anzeigen, ob Bridge aktiviert ist (build-abhängig).",
  "set bridge.enabled ": "Bridge ein-/ausschalten (build-abhängig).",
  "set bridge.delay ": "Bridge-Verzögerung einstellen (build-abhängig).",
  "set bridge.source ": "Bridge-Quelle einstellen (build-abhängig).",
  "set bridge.baud ": "RS232-Bridge-Baudrate einstellen (build-abhängig).",
  "set bridge.channel ": "ESP-NOW-Bridge-Kanal einstellen (build-abhängig).",
  "set bridge.secret ": "ESP-NOW-Bridge-Secret einstellen (build-abhängig).",
  "sensor list": "Sensorvariablen anzeigen.",
  "sensor get ": "Eine Sensorvariable abrufen.",
  "sensor set ": "Eine Sensorvariable einstellen.",
  "io ": "GPIO lesen/einstellen/zurücksetzen/umschalten. z. B. io / io s<hex> / io r<hex> / io t<hex>",
  "filter": "Paketfilterstatus und Blockierungsübersicht pro Typ anzeigen.",
  "filter on": "RF-Paketfilter einschalten.",
  "filter off": "RF-Paketfilter ausschalten.",
  "filter reset": "Filterstandardwerte wiederherstellen.",
  "filter hops ": "Max. Anzahl der Hops pro Payload-Typ einstellen. Beispiel: filter hops 5 20 (type,max_hops). Bloßes \"filter hops\" zeigt die aktuellen Limits.",
  "filter rate ": "Die Rate eines Payload-Typs begrenzen. Beispiel: filter rate 2 20 60 (type,limit,seconds). Bloßes \"filter rate\" zeigt die Konfiguration.",
  "filter channel list": "Blockierte Kanäle anzeigen.",
  "filter channel add ": "Einen Kanal anhand des Namens blockieren. Beispiel: filter channel add Public",
  "filter channel remove ": "Einen Kanal anhand des Namens entsperren.",
  "filter hash ": "Minimale Anzahl der Pfad-Hash-Bytes einstellen (1-3). Bloßes \"filter hash\" zeigt den aktuellen Wert.",
  "filter malformed on": "Öffentlichen Kanaltext mit ungültigem UTF-8 verwerfen.",
  "filter malformed off": "Ungültigen öffentlichen Kanaltext zulassen.",
  "filter count": "Blockierungsstatistiken pro Payload-Typ anzeigen.",
  "get radio.fem.rxgain": "Verstärkungsstatus des externen FEM RX-LNA anzeigen.",
  "set radio.fem.rxgain on": "Externe FEM RX-LNA-Verstärkung einschalten.",
  "set radio.fem.rxgain off": "Externe FEM RX-LNA-Verstärkung ausschalten.",
  "get radio.fem.txgain": "Verstärkungsstatus des externen FEM TX-PA anzeigen.",
  "set radio.fem.txgain on": "Externe FEM TX-PA-Verstärkung einschalten.",
  "set radio.fem.txgain off": "Externe FEM TX-PA-Verstärkung ausschalten.",
  "get radio.watchdog": "Radio-Watchdog-Timeout anzeigen (Minuten).",
  "set radio.watchdog ": "Radio-Watchdog-Timeout in Minuten einstellen (0-120, 0 = aus).",
  "set mqtt.origin ": "MQTT-Origin / Gerätename im Topic einstellen (leer zum Löschen).",
  "get mqtt.origin": "Effektive MQTT-Origin anzeigen.",
  "set mqtt.iata ": "MQTT IATA-Code einstellen.",
  "get mqtt.iata": "MQTT IATA-Code anzeigen.",
  "set mqtt.status on": "Periodische Statuspublikation einschalten.",
  "set mqtt.status off": "Periodische Statuspublikation ausschalten.",
  "get mqtt.status": "MQTT-Verbindungsstatusbericht anzeigen.",
  "set mqtt.packets on": "Publikation pro Paket einschalten.",
  "set mqtt.packets off": "Publikation pro Paket ausschalten.",
  "get mqtt.packets": "Publikationsstatus pro Paket anzeigen.",
  "set mqtt.raw on": "Publikation der rohen Payload einschalten.",
  "set mqtt.raw off": "Publikation der rohen Payload ausschalten.",
  "get mqtt.raw": "Publikationsstatus der rohen Payload anzeigen.",
  "set mqtt.tx ": "TX-Publikation: on|off|advert.",
  "get mqtt.tx": "TX-Publikationsmodus anzeigen (on/off/advert).",
  "set mqtt.rx on": "Publikation empfangener (RX) Pakete einschalten.",
  "set mqtt.rx off": "Publikation empfangener (RX) Pakete ausschalten.",
  "get mqtt.rx": "RX-Publikationsstatus anzeigen.",
  "set mqtt.interval ": "Statusintervall, 1-60 Minuten.",
  "get mqtt.interval": "Statusintervall anzeigen.",
  "set mqtt.ntp ": "NTP-Server einstellen (\"none\" = Standard pool.ntp.org).",
  "get mqtt.ntp": "Konfigurierten NTP-Server anzeigen.",
  "get mqtt.ntp.diag": "NTP-Synchronisationsdiagnostik anzeigen.",
  "set mqtt.owner ": "Öffentlichen Schlüssel des Eigentümers einstellen (64 hex).",
  "get mqtt.owner": "Öffentlichen Schlüssel des Eigentümers anzeigen (nur seriell).",
  "set mqtt.email ": "E-Mail-Adresse des Eigentümers einstellen.",
  "get mqtt.email": "E-Mail-Adresse des Eigentümers anzeigen (nur seriell).",
  "get mqtt.presets": "Eingebaute Broker-Presets anzeigen (z. B. dutchmeshcore-1, dutchmeshcore-2, meshcore-analyzer-eu).",
  "get mqtt.config.valid": "Anzeigen, ob die MQTT-Konfiguration gültig ist.",
  "set mqtt1.preset ": "Preset für Slot 1 (z. B. dutchmeshcore-1, meshcore-analyzer-eu, custom, none).",
  "set mqtt1.server ": "Broker-Host für Slot 1 (custom Preset).",
  "set mqtt1.port ": "Port für Slot 1 (1-65535).",
  "set mqtt1.username ": "Benutzername für Slot 1.",
  "set mqtt1.password ": "Passwort für Slot 1.",
  "set mqtt1.token ": "JWT-Token für Slot 1.",
  "set mqtt1.topic ": "Topic-Vorlage für Slot 1 (nur custom Preset).",
  "set mqtt1.audience ": "JWT-Audience für Slot 1 (leer zum Löschen).",
  "get mqtt1.diag": "Verbindungsdiagnostik für Slot 1.",
  "set mqtt2.preset ": "Preset für Slot 2 (z. B. dutchmeshcore-2, meshcore-analyzer-eu, custom, none).",
  "set mqtt2.server ": "Broker-Host für Slot 2 (custom Preset).",
  "set mqtt2.port ": "Port für Slot 2 (1-65535).",
  "set mqtt2.username ": "Benutzername für Slot 2.",
  "set mqtt2.password ": "Passwort für Slot 2.",
  "set mqtt2.token ": "JWT-Token für Slot 2.",
  "set mqtt2.topic ": "Topic-Vorlage für Slot 2 (nur custom Preset).",
  "set mqtt2.audience ": "JWT-Audience für Slot 2 (leer zum Löschen).",
  "get mqtt2.diag": "Verbindungsdiagnostik für Slot 2.",
  "set mqtt3.preset ": "Preset für Slot 3 (z. B. meshcore-analyzer-eu, custom, none).",
  "set mqtt3.server ": "Broker-Host für Slot 3 (custom Preset).",
  "set mqtt3.port ": "Port für Slot 3 (1-65535).",
  "set mqtt3.username ": "Benutzername für Slot 3.",
  "set mqtt3.password ": "Passwort für Slot 3.",
  "set mqtt3.token ": "JWT-Token für Slot 3.",
  "set mqtt3.topic ": "Topic-Vorlage für Slot 3 (nur custom Preset).",
  "set mqtt3.audience ": "JWT-Audience für Slot 3 (leer zum Löschen).",
  "get mqtt3.diag": "Verbindungsdiagnostik für Slot 3.",
  "set mqtt4.preset ": "Preset für Slot 4 (z. B. meshcore-analyzer-eu, custom, none).",
  "set mqtt4.server ": "Broker-Host für Slot 4 (custom Preset).",
  "set mqtt4.port ": "Port für Slot 4 (1-65535).",
  "set mqtt4.username ": "Benutzername für Slot 4.",
  "set mqtt4.password ": "Passwort für Slot 4.",
  "set mqtt4.token ": "JWT-Token für Slot 4.",
  "set mqtt4.topic ": "Topic-Vorlage für Slot 4 (nur custom Preset).",
  "set mqtt4.audience ": "JWT-Audience für Slot 4 (leer zum Löschen).",
  "get mqtt4.diag": "Verbindungsdiagnostik für Slot 4.",
  "set mqtt5.preset ": "Preset für Slot 5 (z. B. meshcore-analyzer-eu, custom, none).",
  "set mqtt5.server ": "Broker-Host für Slot 5 (custom Preset).",
  "set mqtt5.port ": "Port für Slot 5 (1-65535).",
  "set mqtt5.username ": "Benutzername für Slot 5.",
  "set mqtt5.password ": "Passwort für Slot 5.",
  "set mqtt5.token ": "JWT-Token für Slot 5.",
  "set mqtt5.topic ": "Topic-Vorlage für Slot 5 (nur custom Preset).",
  "set mqtt5.audience ": "JWT-Audience für Slot 5 (leer zum Löschen).",
  "get mqtt5.diag": "Verbindungsdiagnostik für Slot 5.",
  "set mqtt6.preset ": "Preset für Slot 6 (z. B. meshcore-analyzer-eu, custom, none).",
  "set mqtt6.server ": "Broker-Host für Slot 6 (custom Preset).",
  "set mqtt6.port ": "Port für Slot 6 (1-65535).",
  "set mqtt6.username ": "Benutzername für Slot 6.",
  "set mqtt6.password ": "Passwort für Slot 6.",
  "set mqtt6.token ": "JWT-Token für Slot 6.",
  "set mqtt6.topic ": "Topic-Vorlage für Slot 6 (nur custom Preset).",
  "set mqtt6.audience ": "JWT-Audience für Slot 6 (leer zum Löschen).",
  "get mqtt6.diag": "Verbindungsdiagnostik für Slot 6.",
  "set mqtt1.filter ": "Publikationsfilter für Slot 1: all | none | CSV von Typnamen/-nummern. Beispiel: set mqtt1.filter txt_msg,advert",
  "get mqtt1.filter": "Publikationsfilter für Slot 1 anzeigen.",
  "set mqtt2.filter ": "Publikationsfilter für Slot 2: all | none | CSV von Typnamen/-nummern.",
  "get mqtt2.filter": "Publikationsfilter für Slot 2 anzeigen.",
  "set mqtt3.filter ": "Publikationsfilter für Slot 3: all | none | CSV von Typnamen/-nummern.",
  "get mqtt3.filter": "Publikationsfilter für Slot 3 anzeigen.",
  "set mqtt4.filter ": "Publikationsfilter für Slot 4: all | none | CSV von Typnamen/-nummern.",
  "get mqtt4.filter": "Publikationsfilter für Slot 4 anzeigen.",
  "set mqtt5.filter ": "Publikationsfilter für Slot 5: all | none | CSV von Typnamen/-nummern.",
  "get mqtt5.filter": "Publikationsfilter für Slot 5 anzeigen.",
  "set mqtt6.filter ": "Publikationsfilter für Slot 6: all | none | CSV von Typnamen/-nummern.",
  "get mqtt6.filter": "Publikationsfilter für Slot 6 anzeigen.",
  "get mqtt.filter.interval": "MQTT-Publikationsintervall für Filterstatistiken anzeigen (Sekunden).",
  "set mqtt.filter.interval ": "MQTT-Publikationsintervall für Filterstatistiken einstellen (Sekunden). Standard 60.",
  "discover.scopes": "Die Nachbartabelle aktualisieren und jetzt zu MQTT publizieren (einmalig).",
  "get mqtt.neighbors": "Status der periodischen Nachbarpublikation anzeigen.",
  "set mqtt.neighbors on": "Periodische Nachbarpublikation einschalten.",
  "set mqtt.neighbors off": "Periodische Nachbarpublikation ausschalten.",
  "get mqtt.neighbors.interval": "Nachbarpublikationsintervall anzeigen (Stunden).",
  "set mqtt.neighbors.interval ": "Nachbarpublikationsintervall in Stunden einstellen (12-336).",
  "set wifi.ssid ": "WiFi-SSID einstellen (neu starten, um erneut zu verbinden).",
  "set wifi.pwd ": "WiFi-Passwort einstellen (neu starten, um erneut zu verbinden).",
  "set wifi.powersave ": "WiFi-Energiesparmodus: none|min|max.",
  "get wifi.ssid": "WiFi-SSID anzeigen.",
  "get wifi.pwd": "WiFi-Passwort anzeigen.",
  "get wifi.powersave": "WiFi-Energiesparmodus anzeigen.",
  "ota check": "ota.dutchmeshcore.nl auf eine neuere DutchMeshCore-Release über die Observer-WiFi-Verbindung prüfen.",
  "ota update": "Die neueste DutchMeshCore-Firmware über die Observer-WiFi-Verbindung herunterladen und installieren (Pull-basiertes OTA).",
  "set timezone ": "IANA-Zeitzone einstellen (z. B. Europe/Amsterdam).",
  "get timezone": "Zeitzone anzeigen.",
  "set timezone.offset ": "UTC-Offset einstellen (-12..14).",
  "get timezone.offset": "UTC-Offset anzeigen.",
  "set snmp on": "SNMP-Agent einschalten (neu starten, um anzuwenden).",
  "set snmp off": "SNMP-Agent ausschalten (neu starten, um anzuwenden).",
  "get snmp": "Anzeigen, ob SNMP aktiviert ist.",
  "set snmp.community ": "SNMP-Community-String einstellen.",
  "get snmp.community": "SNMP-Community-String anzeigen.",
  "set alert on": "Automatische Störungswarnungen einschalten.",
  "set alert off": "Automatische Störungswarnungen ausschalten.",
  "get alert": "Anzeigen, ob Warnungen aktiviert sind.",
  "set alert.psk ": "PSK des Warnkanals (32 hex; leer zum Löschen).",
  "get alert.psk": "Warnungs-PSK anzeigen (nur seriell).",
  "set alert.hashtag ": "Die PSK des Warnkanals aus einem #hashtag ableiten.",
  "get alert.hashtag": "Warnungs-Hashtag anzeigen.",
  "set alert.region ": "Die Scope-Region für Warnungen überschreiben.",
  "get alert.region": "Region-Override für Warnungen anzeigen.",
  "set alert.wifi ": "Schwelle in Minuten für WiFi-Down-Warnung (0-1440, 0 = aus).",
  "get alert.wifi": "WiFi-Warnungsschwelle anzeigen.",
  "set alert.mqtt ": "Schwelle in Minuten für MQTT-Down-Warnung (0-10080, 0 = aus).",
  "get alert.mqtt": "MQTT-Warnungsschwelle anzeigen.",
  "set alert.interval ": "Minimales Intervall zwischen Wiederholungen (60-10080 Min).",
  "get alert.interval": "Wiederholungsintervall der Warnungen anzeigen.",
  "alert test": "Eine einmalige Testwarnung senden.",
}
